/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        warmCream: {
          50: "var(--color-warm-cream-50)",
          100: "var(--color-warm-cream-100)",
          200: "var(--color-warm-cream-200)",
          300: "var(--color-warm-cream-300)",
          400: "var(--color-warm-cream-400)",
          500: "var(--color-warm-cream-500)",
          600: "var(--color-warm-cream-600)",
          700: "var(--color-warm-cream-700)",
          800: "var(--color-warm-cream-800)",
          900: "var(--color-warm-cream-900)",
        },
        wine: {
          50: "var(--color-wine-50)",
          100: "var(--color-wine-100)",
          200: "var(--color-wine-200)",
          300: "var(--color-wine-300)",
          400: "var(--color-wine-400)",
          500: "var(--color-wine-500)",
          600: "var(--color-wine-600)",
          700: "var(--color-wine-700)",
          800: "var(--color-wine-800)",
          900: "var(--color-wine-900)",
        },
        inkGreen: {
          50: "var(--color-ink-green-50)",
          100: "var(--color-ink-green-100)",
          200: "var(--color-ink-green-200)",
          300: "var(--color-ink-green-300)",
          400: "var(--color-ink-green-400)",
          500: "var(--color-ink-green-500)",
          600: "var(--color-ink-green-600)",
          700: "var(--color-ink-green-700)",
          800: "var(--color-ink-green-800)",
          900: "var(--color-ink-green-900)",
        },
        amber: {
          50: "var(--color-amber-50)",
          100: "var(--color-amber-100)",
          200: "var(--color-amber-200)",
          300: "var(--color-amber-300)",
          400: "var(--color-amber-400)",
          500: "var(--color-amber-500)",
          600: "var(--color-amber-600)",
          700: "var(--color-amber-700)",
          800: "var(--color-amber-800)",
          900: "var(--color-amber-900)",
        },
        stone: {
          50: "var(--color-stone-50)",
          100: "var(--color-stone-100)",
          200: "var(--color-stone-200)",
          300: "var(--color-stone-300)",
          400: "var(--color-stone-400)",
          500: "var(--color-stone-500)",
          600: "var(--color-stone-600)",
          700: "var(--color-stone-700)",
          800: "var(--color-stone-800)",
          900: "var(--color-stone-900)",
        },
        player: {
          red: "var(--color-player-red)",
          blue: "var(--color-player-blue)",
          green: "var(--color-player-green)",
          yellow: "var(--color-player-yellow)",
        },
        bg: "var(--color-bg)",
        surface: "var(--color-surface)",
        text: "var(--color-text)",
        success: "var(--color-success)",
        warning: "var(--color-warning)",
        danger: "var(--color-danger)",
        info: "var(--color-info)",
      },
      fontFamily: {
        display: ["var(--font-display)"],
        body: ["var(--font-body)"],
        mono: ["var(--font-mono)"],
      },
      fontSize: {
        "display-2xl": "var(--type-display-2xl)",
        "display-xl": "var(--type-display-xl)",
        "display-lg": "var(--type-display-lg)",
        "display-md": "var(--type-display-md)",
        "display-sm": "var(--type-display-sm)",
        "body-lg": "var(--type-body-lg)",
        "body-md": "var(--type-body-md)",
        "body-sm": "var(--type-body-sm)",
        label: "var(--type-label)",
        "mono-num": "var(--type-mono-num)",
      },
      borderRadius: {
        8: "var(--radius-8)",
        12: "var(--radius-12)",
        14: "var(--radius-14)",
        20: "var(--radius-20)",
        full: "var(--radius-full)",
      },
      boxShadow: {
        soft: "var(--shadow-soft)",
        medium: "var(--shadow-medium)",
        lifted: "var(--shadow-lifted)",
      },
    },
  },
  plugins: [],
}
